### ISSUE TITLE
DNS SRV support

### ISSUE THREAD

**Issue by Googlom** [krakendio/krakend-grpc#2]
From [thread](https://github.com/devopsfaith/krakend/issues/370).

I think the problem is **Proxy** func which uses grpc client that initialized with host:ip from static configuration file (`remote.Host[0]`), while host and port of services may dynamically change with service discovery(`proxy.Request.URL.Host`):
https://github.com/devopsfaith/krakend-grpc/blob/3c20bd6faa3bef5d1325d9d7f0f37d476d5116b4/grpc.go#L104-L127
https://github.com/devopsfaith/krakend-grpc/blob/3c20bd6faa3bef5d1325d9d7f0f37d476d5116b4/grpc.go#L43

**Comment by kpacha** [comment]
The connection is created long before the first request and it's reused by the internal grpc client. I'd rather load the load balancer and the SD subscriber before establishing the connection
```
lb := sd.NewRandomLB(sd.GetSubscriber(remote))
host, err := lb.Host()
if err != nil {
	host = remote.Host[0]
}
cc, err := grpc.Dial(host, do)
```

**Comment by Googlom** [comment]
I've tried with load balancer. In that case if host which returned with `lb.Host()` (for example, **host1.example.com:11111**) fails, grpc client don't automatically switch to alive host (**host2.example.com:11112**), because **host1.example.com:11111** statically configured when creating connection.

**Comment by kpacha** [comment]
Indeed, that's when a retry strategy should kick in and, after requesting another host from the LB, it should reconnect to the backend service

**Comment by Googlom** [comment]
But where is/should be the reconnection logic in grpc plugin? 
When first host is down krakend don't even try to connect to another host from LB hosts

**Comment by kpacha** [comment]
just before returning the new connection here https://github.com/devopsfaith/krakend-grpc/blob/master/grpc.go#L127 I think a goroutine should be triggered, so the status of the connection can be monitored and restored after an error by calling the `newConnection` function
